# Generated by Django 6.0 on 2025-12-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('extras_deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 'Fase de grupos'), (2, 'Oitavas'), (3, 'Quartas'), (4, 'Semifinais'), (5, '3º lugar + Final')])),
                ('name', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField(help_text='Data limite para palpites desta etapa (todos os jogos).')),
                ('points_exact_score', models.PositiveIntegerField()),
                ('points_result', models.PositiveIntegerField()),
                ('points_one_team_goals', models.PositiveIntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='copa.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('group_name', models.CharField(blank=True, max_length=5, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='copa.stage')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='copa.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='copa.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='copa.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='copa.match')),
            ],
            options={
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='ExtraResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHAMPION', 'Campeã'), ('RUNNER_UP', 'Vice-campeã'), ('THIRD_PLACE', '3º lugar'), ('MOST_RED', 'Mais cartões vermelhos'), ('MOST_YELLOW', 'Mais cartões amarelos'), ('FEWEST_GC', 'Menos gols sofridos'), ('MOST_GC', 'Mais gols sofridos'), ('FEWEST_GF', 'Menos gols marcados'), ('MOST_GF', 'Mais gols marcados'), ('TOP_SCORER', 'Artilheiro (jogador)')], max_length=20)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copa.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_results', to='copa.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ExtraBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHAMPION', 'Campeã'), ('RUNNER_UP', 'Vice-campeã'), ('THIRD_PLACE', '3º lugar'), ('MOST_RED', 'Mais cartões vermelhos'), ('MOST_YELLOW', 'Mais cartões amarelos'), ('FEWEST_GC', 'Menos gols sofridos'), ('MOST_GC', 'Mais gols sofridos'), ('FEWEST_GF', 'Menos gols marcados'), ('MOST_GF', 'Mais gols marcados'), ('TOP_SCORER', 'Artilheiro (jogador)')], max_length=20)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_bets', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copa.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_bets', to='copa.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'user', 'type')},
            },
        ),
    ]
