# Generated by Django 6.0 on 2025-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
