# Generated by Django 6.0 on 2025-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0002_match_away_penalties_match_home_penalties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fase de grupos'), (2, 'Round-of-32'), (3, 'Oitavas de final'), (4, 'Quartas de final'), (5, 'Semifinais'), (6, '3º lugar + Final')]),
        ),
    ]
